Fix writing setup.cfg in binary mode.
This was causing this error:

```
  File "/Users/eric/projects/readthedocs.org/tasks.py", line 65, in prepare
    config.write(configfile)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 919, in write
    self._sections[section].items(), d)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 923, in _write_section
    fp.write("[{}]\n".format(section_name))
TypeError: a bytes-like object is required, not 'str'
```